stock_data = {
    "AAPL": {"Company Name": "Apple Inc.", "Industry": "Electronic Technology","Market Capitalization": 2122302102525},
    "MSFT": {"Company Name": "Microsoft Corporation", "Industry": "Technology Services", "Market Cap": 1777966348754},
    "GOOG": {"Company Name": "Alphabet Inc.", "Industry": "Technology Services", "Market Cap": 1184242673454},
    "GOOGL": {"Company Name": "Alphabet Inc.", "Industry": "Technology Services", "Market Cap": 1184242673454},
    "AMZN": {"Company Name": "Amazon.com, Inc.", "Industry": "Retail Trade", "Market Cap": 971911570617},
    "BRK.B": {"Company Name": "Berkshire Hathaway Inc. New", "Industry": "Finance", "Market Cap": 703424304407},
    "XOM": {"Company Name": "Exxon Mobil Corporation", "Industry": "Energy Minerals", "Market Cap": 466273190232},
    "UNH": {"Company Name": "UnitedHealth Group Incorporated", "Industry": "Health Services", "Market Cap": 463128811145},
    "V": {"Company Name": "Visa Inc.", "Industry": "Commercial Services", "Market Cap": 461034533556},
    "JNJ": {"Company Name": "Johnson & Johnson", "Industry": "Health Technology", "Market Cap": 454920111328},
    "JPM": {"Company Name": "JP Morgan Chase & Co.", "Industry": "Finance", "Market Cap": 409152792460},
    "NVDA": {"Company Name": "NVIDIA Corporation", "Industry": "Electronic Technology", "Market Cap": 406170601501},
    "WMT": {"Company Name": "Walmart Inc.", "Industry": "Retail Trade", "Market Cap": 390523608487},
    "TSLA": {"Company Name": "Tesla, Inc.", "Industry": "Consumer Durables", "Market Cap": 390171883951},
    "MA": {"Company Name": "Mastercard Incorporated", "Industry": "Commercial Services", "Market Cap": 365172034245},
    "META": {"Company Name": "Meta Platforms, Inc.", "Industry": "Technology Services", "Market Cap": 363402133359},
    "PG": {"Company Name": "Procter & Gamble Company (The)", "Industry": "Consumer Non-Durables", "Market Cap": 355004268428},
    "LLY": {"Company Name": "Eli Lilly and Company", "Industry": "Health Technology", "Market Cap": 354496018315},
    "CVX": {"Company Name": "Chevron Corporation", "Industry": "Energy Minerals", "Market Cap": 342408717940},
    "HD": {"Company Name": "Home Depot, Inc. (The)", "Industry": "Retail Trade", "Market Cap": 336198872307},
    "MRK": {"Company Name": "Merck & Company, Inc.", "Industry": "Health Technology", "Market Cap": 283381201972},
    "BAC": {"Company Name": "Bank of America Corporation", "Industry": "Finance", "Market Cap": 276533245276},
    "ABBV": {"Company Name": "AbbVie Inc.", "Industry": "Health Technology", "Market Cap": 269198099112},
    "PFE": {"Company Name": "Pfizer, Inc.", "Industry": "Health Technology", "Market Cap": 267811227419},
    "KO": {"Company Name": "Coca-Cola Company (The)", "Industry": "Consumer Non-Durables", "Market Cap": 264703477896},
    "AVGO": {"Company Name": "Broadcom Inc.", "Industry": "Electronic Technology", "Market Cap": 243184660701},
    "PEP": {"Company Name": "PepsiCo, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 242173726507},
    "ORCL": {"Company Name": "Oracle Corporation", "Industry": "Technology Services", "Market Cap": 239373331806},
    "TMO": {"Company Name": "Thermo Fisher Scientific Inc", "Industry": "Health Technology", "Market Cap": 228077395391},
    "COST": {"Company Name": "Costco Wholesale Corporation", "Industry": "Retail Trade", "Market Cap": 214068194827},
    "CSCO": {"Company Name": "Cisco Systems, Inc.", "Industry": "Electronic Technology", "Market Cap": 201297048340},
    "NKE": {"Company Name": "Nike, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 198314644569},
    "DHR": {"Company Name": "Danaher Corporation", "Industry": "Health Technology", "Market Cap": 198231523107},
    "MCD": {"Company Name": "McDonald's Corporation", "Industry": "Consumer Services", "Market Cap": 195330128788},
    "ABT": {"Company Name": "Abbott Laboratories", "Industry": "Health Technology", "Market Cap": 194164371689},
    "ACN": {"Company Name": "Accenture plc", "Industry": "Technology Services", "Market Cap": 186876986241},
    "TMUS": {"Company Name": "T-Mobile US, Inc.", "Industry": "Communications", "Market Cap": 186511156901},
    "DIS": {"Company Name": "Walt Disney Company (The)", "Industry": "Consumer Services", "Market Cap": 182012717162},
    "VZ": {"Company Name": "Verizon Communications Inc.", "Industry": "Communications", "Market Cap": 175594370543},
    "NEE": {"Company Name": "NextEra Energy, Inc.", "Industry": "Utilities", "Market Cap": 169048004652},
    "CMCSA": {"Company Name": "Comcast Corporation", "Industry": "Consumer Services", "Market Cap": 167272677845},
    "WFC": {"Company Name": "Wells Fargo & Company", "Industry": "Finance", "Market Cap": 163203335085},
    "LIN": {"Company Name": "Linde plc", "Industry": "Process Industries", "Market Cap": 162606368616},
    "TXN": {"Company Name": "Texas Instruments Incorporated", "Industry": "Electronic Technology", "Market Cap": 161665754258},
    "ADBE": {"Company Name": "Adobe Inc.", "Industry": "Technology Services", "Market Cap": 160176647870},
    "UPS": {"Company Name": "United Parcel Service, Inc.", "Industry": "Transportation", "Market Cap": 158218985196},
    "PM": {"Company Name": "Philip Morris International Inc", "Industry": "Consumer Non-Durables", "Market Cap": 157252522105},
    "SCHW": {"Company Name": "Charles Schwab Corporation (The)", "Industry": "Finance", "Market Cap": 155835401032},
    "MS": {"Company Name": "Morgan Stanley", "Industry": "Finance", "Market Cap": 153005599656},
    "BMY": {"Company Name": "Bristol-Myers Squibb Company", "Industry": "Health Technology", "Market Cap": 152233063943},
    "COP": {"Company Name": "ConocoPhillips", "Industry": "Energy Minerals", "Market Cap": 149727915989},
    "CRM": {"Company Name": "Salesforce, Inc.", "Industry": "Technology Services", "Market Cap": 149600006104},
    "RTX": {"Company Name": "Raytheon Technologies Corporation", "Industry": "Electronic Technology", "Market Cap": 148005720888},
    "NFLX": {"Company Name": "Netflix, Inc.", "Industry": "Technology Services", "Market Cap": 146914622417},
    "HON": {"Company Name": "Honeywell International Inc.", "Industry": "Electronic Technology", "Market Cap": 145208160057},
    "AMGN": {"Company Name": "Amgen Inc.", "Industry": "Health Technology", "Market Cap": 144557273896},
    "T": {"Company Name": "AT&T Inc.", "Industry": "Communications", "Market Cap": 138335068913},
    "QCOM": {"Company Name": "QUALCOMM Incorporated", "Industry": "Electronic Technology", "Market Cap": 136302385895},
    "CAT": {"Company Name": "Caterpillar, Inc.", "Industry": "Producer Manufacturing", "Market Cap": 132740819979},
    "UNP": {"Company Name": "Union Pacific Corporation", "Industry": "Transportation", "Market Cap": 131991594331},
    "IBM": {"Company Name": "International Business Machines Corporation", "Industry": "Technology Services", "Market Cap": 131595600834},
    "DE": {"Company Name": "Deere & Company", "Industry": "Producer Manufacturing", "Market Cap": 130058278492},
    "BA": {"Company Name": "Boeing Company (The)", "Industry": "Electronic Technology", "Market Cap": 127731127075},
    "LOW": {"Company Name": "Lowe's Companies, Inc.", "Industry": "Retail Trade", "Market Cap": 127144760242},
    "GS": {"Company Name": "Goldman Sachs Group, Inc. (The)", "Industry": "Finance", "Market Cap": 125274478284},
    "INTC": {"Company Name": "Intel Corporation", "Industry": "Electronic Technology", "Market Cap": 125006833778},
    "SBUX": {"Company Name": "Starbucks Corporation", "Industry": "Consumer Services", "Market Cap": 121494633417},
    "LMT": {"Company Name": "Lockheed Martin Corporation", "Industry": "Electronic Technology", "Market Cap": 121010034477},
    "SPGI": {"Company Name": "S&P Global Inc.", "Industry": "Commercial Services", "Market Cap": 119819457931},
    "CVS": {"Company Name": "CVS Health Corporation", "Industry": "Retail Trade", "Market Cap": 117179570233},
    "AXP": {"Company Name": "American Express Company", "Industry": "Finance", "Market Cap": 115761283251},
    "PLD": {"Company Name": "Prologis, Inc.", "Industry": "Finance", "Market Cap": 115332762554},
    "AMD": {"Company Name": "Advanced Micro Devices, Inc.", "Industry": "Electronic Technology", "Market Cap": 114154815321},
    "ELV": {"Company Name": "Elevance Health, Inc.", "Industry": "Health Services", "Market Cap": 113939856600},
    "BLK": {"Company Name": "BlackRock, Inc.", "Industry": "Finance", "Market Cap": 113241456689},
    "INTU": {"Company Name": "Intuit Inc.", "Industry": "Technology Services", "Market Cap": 111443091363},
    "AMT": {"Company Name": "American Tower Corporation (REIT)", "Industry": "Finance", "Market Cap": 108118277370},
    "GILD": {"Company Name": "Gilead Sciences, Inc.", "Industry": "Health Technology", "Market Cap": 107513788338},
    "MDT": {"Company Name": "Medtronic plc.", "Industry": "Health Technology", "Market Cap": 106214875259},
    "ADP": {"Company Name": "Automatic Data Processing, Inc.", "Industry": "Technology Services", "Market Cap": 101325833537},
    "SYK": {"Company Name": "Stryker Corporation", "Industry": "Health Technology", "Market Cap": 97010515286},
    "C": {"Company Name": "Citigroup, Inc.", "Industry": "Finance", "Market Cap": 95080109415},
    "CI": {"Company Name": "Cigna Corporation", "Industry": "Health Services", "Market Cap": 94846357195},
    "TJX": {"Company Name": "TJX Companies, Inc. (The)", "Industry": "Retail Trade", "Market Cap": 94658897884},
    "CB": {"Company Name": "Chubb Limited", "Industry": "Finance", "Market Cap": 93635348627},
    "EL": {"Company Name": "Estee Lauder Companies, Inc. (The)", "Industry": "Consumer Non-Durables", "Market Cap": 93574031756},
    "AMAT": {"Company Name": "Applied Materials, Inc.", "Industry": "Producer Manufacturing", "Market Cap": 93024200134},
    "MDLZ": {"Company Name": "Mondelez International, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 91168695998},
    "PYPL": {"Company Name": "PayPal Holdings, Inc.", "Industry": "Commercial Services", "Market Cap": 90951409309},
    "ISRG": {"Company Name": "Intuitive Surgical, Inc.", "Industry": "Health Technology", "Market Cap": 90798627654},
    "BKNG": {"Company Name": "Booking Holdings Inc. Common Stock", "Industry": "Consumer Services", "Market Cap": 87538725092},
    "MMC": {"Company Name": "Marsh & McLennan Companies, Inc.", "Industry": "Finance", "Market Cap": 86385014763},
    "GE": {"Company Name": "General Electric Company", "Industry": "Producer Manufacturing", "Market Cap": 86167806309},
    "ADI": {"Company Name": "Analog Devices, Inc.", "Industry": "Electronic Technology", "Market Cap": 85902943404},
    "NOW": {"Company Name": "ServiceNow, Inc.", "Industry": "Technology Services", "Market Cap": 83643823454},
    "SLB": {"Company Name": "Schlumberger N.V.", "Industry": "Industrial Services", "Market Cap": 82243638916},
    "MO": {"Company Name": "Altria Group, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 81364639112},
    "DUK": {"Company Name": "Duke Energy Corporation (Holding Company)", "Industry": "Utilities", "Market Cap": 80918194564},
    "REGN": {"Company Name": "Regeneron Pharmaceuticals, Inc.", "Industry": "Health Technology", "Market Cap": 77805087767},
    "PGR": {"Company Name": "Progressive Corporation (The)", "Industry": "Finance", "Market Cap": 77779167632},
    "EOG": {"Company Name": "EOG Resources, Inc.", "Industry": "Energy Minerals", "Market Cap": 76624961922},
    "SO": {"Company Name": "Southern Company (The)", "Industry": "Utilities", "Market Cap": 76577244392},
    "VRTX": {"Company Name": "Vertex Pharmaceuticals Incorporated", "Industry": "Health Technology", "Market Cap": 76044847183},
    "NOC": {"Company Name": "Northrop Grumman Corporation", "Industry": "Electronic Technology", "Market Cap": 75106055162},
    "ZTS": {"Company Name": "Zoetis Inc.", "Industry": "Health Technology", "Market Cap": 74529573782},
    "TGT": {"Company Name": "Target Corporation", "Industry": "Retail Trade", "Market Cap": 73534536736},
    "BDX": {"Company Name": "Becton, Dickinson and Company", "Industry": "Health Technology", "Market Cap": 72374628133},
    "MRNA": {"Company Name": "Moderna, Inc.", "Industry": "Health Technology", "Market Cap": 72248980311},
    "HCA": {"Company Name": "HCA Healthcare, Inc.", "Industry": "Health Services", "Market Cap": 72135157851},
    "MMM": {"Company Name": "3M Company", "Industry": "Health Technology", "Market Cap": 71497300066},
    "ITW": {"Company Name": "Illinois Tool Works Inc.", "Industry": "Producer Manufacturing", "Market Cap": 71365539926},
    "USB": {"Company Name": "U.S. Bancorp", "Industry": "Finance", "Market Cap": 70710339941},
    "APD": {"Company Name": "Air Products and Chemicals, Inc.", "Industry": "Process Industries", "Market Cap": 68825039664},
    "CSX": {"Company Name": "CSX Corporation", "Industry": "Transportation", "Market Cap": 68307261913},
    "PNC": {"Company Name": "PNC Financial Services Group, Inc. (The)", "Industry": "Finance", "Market Cap": 68088321727},
    "GD": {"Company Name": "General Dynamics Corporation", "Industry": "Electronic Technology", "Market Cap": 68005781685},
    "EQIX": {"Company Name": "Equinix, Inc.", "Industry": "Technology Services", "Market Cap": 67121599875},
    "BSX": {"Company Name": "Boston Scientific Corporation", "Industry": "Distribution Services", "Market Cap": 66903258545},
    "ETN": {"Company Name": "Eaton Corporation, PLC", "Industry": "Producer Manufacturing", "Market Cap": 65505171681},
    "CCI": {"Company Name": "Crown Castle Inc.", "Industry": "Finance", "Market Cap": 65498510628},
    "AON": {"Company Name": "Aon plc", "Industry": "Finance", "Market Cap": 65338635818},
    "FISV": {"Company Name": "Fiserv, Inc.", "Industry": "Finance", "Market Cap": 65039574399},
    "FCX": {"Company Name": "Freeport-McMoRan, Inc.", "Industry": "Non-Energy Minerals", "Market Cap": 64462657719},
    "CL": {"Company Name": "Colgate-Palmolive Company", "Industry": "Consumer Non-Durables", "Market Cap": 64177853946},
    "LRCX": {"Company Name": "Lam Research Corporation", "Industry": "Producer Manufacturing", "Market Cap": 64103750254},
    "CME": {"Company Name": "CME Group Inc.", "Industry": "Finance", "Market Cap": 63565312910},
    "SHW": {"Company Name": "Sherwin-Williams Company (The)", "Industry": "Process Industries", "Market Cap": 63163621690},
    "WM": {"Company Name": "Waste Management, Inc.", "Industry": "Industrial Services", "Market Cap": 62671637766},
    "TFC": {"Company Name": "Truist Financial Corporation", "Industry": "Finance", "Market Cap": 62596831389},
    "HUM": {"Company Name": "Humana Inc.", "Industry": "Health Services", "Market Cap": 62577272715},
    "MU": {"Company Name": "Micron Technology, Inc.", "Industry": "Electronic Technology", "Market Cap": 62491679437},
    "ICE": {"Company Name": "Intercontinental Exchange Inc.", "Industry": "Finance", "Market Cap": 60898884163},
    "ATVI": {"Company Name": "Activision Blizzard, Inc", "Industry": "Technology Services", "Market Cap": 60183887162},
    "CHTR": {"Company Name": "Charter Communications, Inc.", "Industry": "Consumer Services", "Market Cap": 60006997040},
    "OXY": {"Company Name": "Occidental Petroleum Corporation", "Industry": "Energy Minerals", "Market Cap": 59752012540},
    "KLAC": {"Company Name": "KLA Corporation", "Industry": "Electronic Technology", "Market Cap": 59389898554},
    "NSC": {"Company Name": "Norfolk Southern Corporation", "Industry": "Transportation", "Market Cap": 58843969176},
    "EMR": {"Company Name": "Emerson Electric Company", "Industry": "Electronic Technology", "Market Cap": 57986774199},
    "MCO": {"Company Name": "Moody's Corporation", "Industry": "Commercial Services", "Market Cap": 57231677928},
    "PXD": {"Company Name": "Pioneer Natural Resources Company", "Industry": "Energy Minerals", "Market Cap": 56828864803},
    "MPC": {"Company Name": "Marathon Petroleum Corporation", "Industry": "Energy Minerals", "Market Cap": 56712651446},
    "MET": {"Company Name": "MetLife, Inc.", "Industry": "Finance", "Market Cap": 56013036223},
    "GM": {"Company Name": "General Motors Company", "Industry": "Consumer Durables", "Market Cap": 54455310077},
    "MCK": {"Company Name": "McKesson Corporation", "Industry": "Distribution Services", "Market Cap": 54000631279},
    "F": {"Company Name": "Ford Motor Company", "Industry": "Consumer Durables", "Market Cap": 53995237874},
    "D": {"Company Name": "Dominion Energy, Inc.", "Industry": "Utilities", "Market Cap": 52421343178},
    "MNST": {"Company Name": "Monster Beverage Corporation", "Industry": "Consumer Non-Durables", "Market Cap": 52195235458},
    "VLO": {"Company Name": "Valero Energy Corporation", "Industry": "Energy Minerals", "Market Cap": 52169013738},
    "PSA": {"Company Name": "Public Storage", "Industry": "Finance", "Market Cap": 52003014290},
    "DG": {"Company Name": "Dollar General Corporation", "Industry": "Retail Trade", "Market Cap": 51994554613},
    "KHC": {"Company Name": "The Kraft Heinz Company", "Industry": "Consumer Non-Durables", "Market Cap": 51973787732},
    "SNPS": {"Company Name": "Synopsys, Inc.", "Industry": "Technology Services", "Market Cap": 50770167103},
    "ORLY": {"Company Name": "O'Reilly Automotive, Inc.", "Industry": "Retail Trade", "Market Cap": 50739674010},
    "MAR": {"Company Name": "Marriott International", "Industry": "Consumer Services", "Market Cap": 50643174233},
    "SRE": {"Company Name": "DBA Sempra", "Industry": "Utilities", "Market Cap": 50585667579},
    "KDP": {"Company Name": "Keurig Dr Pepper Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 50376055488},
    "AEP": {"Company Name": "American Electric Power Company, Inc.", "Industry": "Utilities", "Market Cap": 49541602018},
    "GIS": {"Company Name": "General Mills, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 48660571818},
    "PSX": {"Company Name": "Phillips 66", "Industry": "Energy Minerals", "Market Cap": 48614951740},
    "FDX": {"Company Name": "FedEx Corporation", "Industry": "Transportation", "Market Cap": 48432487137},
    "APH": {"Company Name": "Amphenol Corporation", "Industry": "Electronic Technology", "Market Cap": 48143149474},
    "EW": {"Company Name": "Edwards Lifesciences Corporation", "Industry": "Health Technology", "Market Cap": 48069753723},
    "ADM": {"Company Name": "Archer-Daniels-Midland Company", "Industry": "Process Industries", "Market Cap": 48006317895},
    "ROP": {"Company Name": "Roper Technologies, Inc.", "Industry": "Technology Services", "Market Cap": 47853870105},
    "AIG": {"Company Name": "American International Group, Inc. New", "Industry": "Finance", "Market Cap": 47312965383},
    "JCI": {"Company Name": "Johnson Controls International plc", "Industry": "Producer Manufacturing", "Market Cap": 46956807884},
    "HES": {"Company Name": "Hess Corporation", "Industry": "Energy Minerals", "Market Cap": 46471334619},
    "A": {"Company Name": "Agilent Technologies, Inc.", "Industry": "Health Technology", "Market Cap": 46332312268},
    "CDNS": {"Company Name": "Cadence Design Systems, Inc.", "Industry": "Technology Services", "Market Cap": 46101547890},
    "KMB": {"Company Name": "Kimberly-Clark Corporation", "Industry": "Consumer Non-Durables", "Market Cap": 45979925006},
    "HSY": {"Company Name": "The Hershey Company", "Industry": "Consumer Non-Durables", "Market Cap": 45977462491},
    "CTAS": {"Company Name": "Cintas Corporation", "Industry": "Consumer Services", "Market Cap": 45346106019},
    "TRV": {"Company Name": "The Travelers Companies, Inc.", "Industry": "Finance", "Market Cap": 44992384374},
    "AZO": {"Company Name": "AutoZone, Inc.", "Industry": "Retail Trade", "Market Cap": 44853110203},
    "CTVA": {"Company Name": "Corteva, Inc.", "Industry": "Process Industries", "Market Cap": 44712910943},
    "AFL": {"Company Name": "AFLAC Incorporated", "Industry": "Finance", "Market Cap": 44644421526},
    "CNC": {"Company Name": "Centene Corporation", "Industry": "Health Services", "Market Cap": 44270183878},
    "MSI": {"Company Name": "Motorola Solutions, Inc.", "Industry": "Electronic Technology", "Market Cap": 44260357986},
    "NXPI": {"Company Name": "NXP Semiconductors N.V.", "Industry": "Electronic Technology", "Market Cap": 44107345780},
    "ECL": {"Company Name": "Ecolab Inc.", "Industry": "Process Industries", "Market Cap": 43686929842},
    "PAYX": {"Company Name": "Paychex, Inc.", "Industry": "Technology Services", "Market Cap": 43201915795},
    "ADSK": {"Company Name": "Autodesk, Inc.", "Industry": "Technology Services", "Market Cap": 43144871115},
    "EXC": {"Company Name": "Exelon Corporation", "Industry": "Utilities", "Market Cap": 43108529212},
    "KMI": {"Company Name": "Kinder Morgan, Inc.", "Industry": "Industrial Services", "Market Cap": 42459843938},
    "NEM": {"Company Name": "Newmont Corporation", "Industry": "Non-Energy Minerals", "Market Cap": 42385651504},
    "CMG": {"Company Name": "Chipotle Mexican Grill, Inc.", "Industry": "Consumer Services", "Market Cap": 41927348392},
    "DVN": {"Company Name": "Devon Energy Corporation", "Industry": "Energy Minerals", "Market Cap": 41856410984},
    "O": {"Company Name": "Realty Income Corporation", "Industry": "Finance", "Market Cap": 41737091938},
    "TT": {"Company Name": "Trane Technologies plc", "Industry": "Producer Manufacturing", "Market Cap": 41540525991},
    "BIIB": {"Company Name": "Biogen Inc.", "Industry": "Health Technology", "Market Cap": 41483922476},
    "DXCM": {"Company Name": "DexCom, Inc.", "Industry": "Health Technology", "Market Cap": 41383694492},
    "MCHP": {"Company Name": "Microchip Technology Incorporated", "Industry": "Electronic Technology", "Market Cap": 41382650930},
    "SPG": {"Company Name": "Simon Property Group, Inc.", "Industry": "Finance", "Market Cap": 41191896897},
    "STZ": {"Company Name": "Constellation Brands, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 41188739883},
    "DOW": {"Company Name": "Dow Inc.", "Industry": "Process Industries", "Market Cap": 41183993232},
    "AJG": {"Company Name": "Arthur J. Gallagher & Co.", "Industry": "Finance", "Market Cap": 41111692044},
    "FIS": {"Company Name": "Fidelity National Information Services, Inc.", "Industry": "Commercial Services", "Market Cap": 41109327957},
    "ROST": {"Company Name": "Ross Stores, Inc.", "Industry": "Retail Trade", "Market Cap": 40894056511},
    "LVS": {"Company Name": "Las Vegas Sands Corp.", "Industry": "Consumer Services", "Market Cap": 40882894897},
    "IQV": {"Company Name": "IQVIA Holdings, Inc.", "Industry": "Health Services", "Market Cap": 40769934555},
    "SYY": {"Company Name": "Sysco Corporation", "Industry": "Transportation", "Market Cap": 40668093246},
    "PH": {"Company Name": "Parker-Hannifin Corporation", "Industry": "Producer Manufacturing", "Market Cap": 40470917420},
    "MSCI": {"Company Name": "MSCI Inc", "Industry": "Technology Services", "Market Cap": 40302909774},
    "WMB": {"Company Name": "Williams Companies, Inc. (The)", "Industry": "Energy Minerals", "Market Cap": 40156480135},
    "NUE": {"Company Name": "Nucor Corporation", "Industry": "Non-Energy Minerals", "Market Cap": 39946421432},
    "TEL": {"Company Name": "TE Connectivity Ltd. New Switzerland Registered Shares", "Industry": "Electronic Technology", "Market Cap": 39377828579},
    "XEL": {"Company Name": "Xcel Energy Inc.", "Industry": "Utilities", "Market Cap": 39374526043},
    "RSG": {"Company Name": "Republic Services, Inc.", "Industry": "Industrial Services", "Market Cap": 38953435558},
    "BK": {"Company Name": "The Bank of New York Mellon Corporation", "Industry": "Finance", "Market Cap": 38926760209},
    "IDXX": {"Company Name": "IDEXX Laboratories, Inc.", "Industry": "Health Technology", "Market Cap": 38899951491},
    "COF": {"Company Name": "Capital One Financial Corporation", "Industry": "Finance", "Market Cap": 38559185973},
    "HAL": {"Company Name": "Halliburton Company", "Industry": "Energy Minerals", "Market Cap": 38292329908},
    "LHX": {"Company Name": "L3Harris Technologies, Inc.", "Industry": "Electronic Technology", "Market Cap": 38032959602},
    "CARR": {"Company Name": "Carrier Global Corporation", "Industry": "Producer Manufacturing", "Market Cap": 37840831726},
    "FTNT": {"Company Name": "Fortinet, Inc.", "Industry": "Electronic Technology", "Market Cap": 37811824703},
    "DD": {"Company Name": "DuPont de Nemours, Inc.", "Industry": "Process Industries", "Market Cap": 37134973297},
    "TDG": {"Company Name": "Transdigm Group Inc.", "Industry": "Electronic Technology", "Market Cap": 36985603214},
    "PRU": {"Company Name": "Prudential Financial, Inc.", "Industry": "Finance", "Market Cap": 36652799438},
    "HLT": {"Company Name": "Hilton Worldwide Holdings Inc.", "Industry": "Consumer Services", "Market Cap": 36511563263},
    "ALL": {"Company Name": "Allstate Corporation (The)", "Industry": "Finance", "Market Cap": 36352276909},
    "YUM": {"Company Name": "Yum! Brands, Inc.", "Industry": "Consumer Services", "Market Cap": 36306748904},
    "ANET": {"Company Name": "Arista Networks, Inc.", "Industry": "Electronic Technology", "Market Cap": 35807001092},
    "CMI": {"Company Name": "Cummins Inc.", "Industry": "Producer Manufacturing", "Market Cap": 35271131608},
    "PCAR": {"Company Name": "PACCAR Inc.", "Industry": "Producer Manufacturing", "Market Cap": 35260151440},
    "AMP": {"Company Name": "Ameriprise Financial, Inc.", "Industry": "Finance", "Market Cap": 35242184951},
    "EA": {"Company Name": "Electronic Arts Inc.", "Industry": "Technology Services", "Market Cap": 34902062261},
    "ED": {"Company Name": "Consolidated Edison, Inc.", "Industry": "Utilities", "Market Cap": 34609773718},
    "ODFL": {"Company Name": "Old Dominion Freight Line, Inc.", "Industry": "Transportation", "Market Cap": 34608370102},
    "OTIS": {"Company Name": "Otis Worldwide Corporation", "Industry": "Producer Manufacturing", "Market Cap": 34534984974},
    "MTD": {"Company Name": "Mettler-Toledo International, Inc.", "Industry": "Health Technology", "Market Cap": 34248555909},
    "WELL": {"Company Name": "Welltower Inc.", "Industry": "Finance", "Market Cap": 34068793902},
    "ABC": {"Company Name": "AmerisourceBergen Corporation", "Industry": "Distribution Services", "Market Cap": 33914754987},
    "CTSH": {"Company Name": "Cognizant Technology Solutions Corporation", "Industry": "Technology Services", "Market Cap": 33456285465},
    "AME": {"Company Name": "AMETEK, Inc.", "Industry": "Producer Manufacturing", "Market Cap": 33426196937},
    "SBAC": {"Company Name": "SBA Communications Corporation", "Industry": "Finance", "Market Cap": 33084959736},
    "DHI": {"Company Name": "D.R. Horton, Inc.", "Industry": "Consumer Durables", "Market Cap": 32935336621},
    "ENPH": {"Company Name": "Enphase Energy, Inc.", "Industry": "Electronic Technology", "Market Cap": 32855448887},
    "VICI": {"Company Name": "VICI Properties Inc.", "Industry": "Finance", "Market Cap": 32764591012},
    "KR": {"Company Name": "Kroger Company (The)", "Industry": "Retail Trade", "Market Cap": 32691584836},
    "CSGP": {"Company Name": "CoStar Group, Inc.", "Industry": "Technology Services", "Market Cap": 32665345774},
    "DLTR": {"Company Name": "Dollar Tree, Inc.", "Industry": "Retail Trade", "Market Cap": 32430067196},
    "ROK": {"Company Name": "Rockwell Automation, Inc.", "Industry": "Electronic Technology", "Market Cap": 32290690074},
    "WBD": {"Company Name": "Warner Bros. Discovery, Inc. Series A", "Industry": "Consumer Services", "Market Cap": 31933406422},
    "KEYS": {"Company Name": "Keysight Technologies Inc.", "Industry": "Electronic Technology", "Market Cap": 31811287192},
    "BKR": {"Company Name": "Baker Hughes Company", "Industry": "Industrial Services", "Market Cap": 31766729095},
    "PCG": {"Company Name": "Pacific Gas & Electric Co.", "Industry": "Utilities", "Market Cap": 31743570700},
    "OKE": {"Company Name": "ONEOK, Inc.", "Industry": "Industrial Services", "Market Cap": 31702437243},
    "WBA": {"Company Name": "Walgreens Boots Alliance, Inc.", "Industry": "Retail Trade", "Market Cap": 31619379646},
    "BF.B": {"Company Name": "Brown Forman Inc", "Industry": "Consumer Non-Durables", "Market Cap": 31445486283},
    "RMD": {"Company Name": "ResMed Inc.", "Industry": "Health Technology", "Market Cap": 31347502777},
    "PEG": {"Company Name": "Public Service Enterprise Group Incorporated", "Industry": "Utilities", "Market Cap": 31329054477},
    "NDAQ": {"Company Name": "Nasdaq, Inc.", "Industry": "Finance", "Market Cap": 30945699113},
    "PPG": {"Company Name": "PPG Industries, Inc.", "Industry": "Process Industries", "Market Cap": 30934303862},
    "GLW": {"Company Name": "Corning Incorporated", "Industry": "Electronic Technology", "Market Cap": 30905949380},
    "DLR": {"Company Name": "Digital Realty Trust, Inc.", "Industry": "Finance", "Market Cap": 30845389615},
    "WEC": {"Company Name": "WEC Energy Group, Inc.", "Industry": "Utilities", "Market Cap": 30552989717},
    "LYB": {"Company Name": "LyondellBasell Industries NV", "Industry": "Process Industries", "Market Cap": 30501241699},
    "ILMN": {"Company Name": "Illumina, Inc.", "Industry": "Health Technology", "Market Cap": 30476875591},
    "STT": {"Company Name": "State Street Corporation", "Industry": "Finance", "Market Cap": 30224861578},
    "CPRT": {"Company Name": "Copart, Inc.", "Industry": "Commercial Services", "Market Cap": 29797327890},
    "ES": {"Company Name": "Eversource Energy (D/B/A)", "Industry": "Utilities", "Market Cap": 29651408309},
    "IFF": {"Company Name": "International Flavors & Fragrances, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 29473635683},
    "GPN": {"Company Name": "Global Payments Inc.", "Industry": "Commercial Services", "Market Cap": 29297964576},
    "AWK": {"Company Name": "American Water Works Company, Inc.", "Industry": "Utilities", "Market Cap": 28987000434},
    "DFS": {"Company Name": "Discover Financial Services", "Industry": "Finance", "Market Cap": 28978321161},
    "GWW": {"Company Name": "W.W. Grainger, Inc.", "Industry": "Distribution Services", "Market Cap": 28930022866},
    "VRSK": {"Company Name": "Verisk Analytics, Inc.", "Industry": "Technology Services", "Market Cap": 28612741244},
    "ALB": {"Company Name": "Albemarle Corporation", "Industry": "Process Industries", "Market Cap": 28492731787},
    "LEN": {"Company Name": "Lennar Corporation", "Industry": "Consumer Durables", "Market Cap": 28247470443},
    "ON": {"Company Name": "ON Semiconductor Corporation", "Industry": "Electronic Technology", "Market Cap": 28077261459},
    "FAST": {"Company Name": "Fastenal Company", "Industry": "Distribution Services", "Market Cap": 28076689957},
    "HPQ": {"Company Name": "HP Inc.", "Industry": "Electronic Technology", "Market Cap": 28040262211},
    "CEG": {"Company Name": "Constellation Energy Corporation", "Industry": "Utilities", "Market Cap": 27580689654},
    "WTW": {"Company Name": "Willis Towers Watson Public Limited Company", "Industry": "Finance", "Market Cap": 27571367841},
    "APTV": {"Company Name": "Aptiv PLC", "Industry": "Producer Manufacturing", "Market Cap": 27547443807},
    "URI": {"Company Name": "United Rentals, Inc.", "Industry": "Finance", "Market Cap": 27152985166},
    "CBRE": {"Company Name": "CBRE Group Inc", "Industry": "Finance", "Market Cap": 27054670630},
    "TROW": {"Company Name": "T. Rowe Price Group, Inc.", "Industry": "Finance", "Market Cap": 26719687650},
    "IT": {"Company Name": "Gartner, Inc.", "Industry": "Technology Services", "Market Cap": 26546660585},
    "EFX": {"Company Name": "Equifax, Inc.", "Industry": "Commercial Services", "Market Cap": 26472268768},
    "CDW": {"Company Name": "CDW Corporation", "Industry": "Technology Services", "Market Cap": 26183263708},
    "EIX": {"Company Name": "Edison International", "Industry": "Utilities", "Market Cap": 26139321695},
    "ZBH": {"Company Name": "Zimmer Biomet Holdings, Inc.", "Industry": "Health Technology", "Market Cap": 25853813373},
    "MTB": {"Company Name": "M&T Bank Corporation", "Industry": "Finance", "Market Cap": 25831948062},
    "ARE": {"Company Name": "Alexandria Real Estate Equities, Inc.", "Industry": "Finance", "Market Cap": 25577926050},
    "FANG": {"Company Name": "Diamondback Energy, Inc.", "Industry": "Energy Minerals", "Market Cap": 25577874089},
    "HRL": {"Company Name": "Hormel Foods Corporation", "Industry": "Consumer Non-Durables", "Market Cap": 25425117095},
    "DAL": {"Company Name": "Delta Air Lines, Inc.", "Industry": "Transportation", "Market Cap": 25391057860},
    "EBAY": {"Company Name": "eBay Inc.", "Industry": "Retail Trade", "Market Cap": 25195660211},
    "ULTA": {"Company Name": "Ulta Beauty, Inc.", "Industry": "Retail Trade", "Market Cap": 25024687355},
    "FE": {"Company Name": "FirstEnergy Corp.", "Industry": "Utilities", "Market Cap": 24636844347},
    "DTE": {"Company Name": "DTE Energy Company", "Industry": "Utilities", "Market Cap": 24550067783},
    "RJF": {"Company Name": "Raymond James Financial, Inc.", "Industry": "Finance", "Market Cap": 24480689826},
    "TSCO": {"Company Name": "Tractor Supply Company", "Industry": "Retail Trade", "Market Cap": 24383656553},
    "HIG": {"Company Name": "Hartford Financial Services Group, Inc. (The)", "Industry": "Finance", "Market Cap": 24255044022},
    "VMC": {"Company Name": "Vulcan Materials Company (Holding Company)", "Industry": "Non-Energy Minerals", "Market Cap": 24030889096},
    "K": {"Company Name": "Kellogg Company", "Industry": "Consumer Non-Durables", "Market Cap": 23971587840},
    "FITB": {"Company Name": "Fifth Third Bancorp", "Industry": "Finance", "Market Cap": 23955227701},
    "GPC": {"Company Name": "Genuine Parts Company", "Industry": "Distribution Services", "Market Cap": 23849209049},
    "AVB": {"Company Name": "AvalonBay Communities, Inc.", "Industry": "Finance", "Market Cap": 23820320487},
    "FTV": {"Company Name": "Fortive Corporation", "Industry": "Electronic Technology", "Market Cap": 23733458598},
    "WY": {"Company Name": "Weyerhaeuser Company", "Industry": "Finance", "Market Cap": 23645013745},
    "ACGL": {"Company Name": "Arch Capital Group Ltd.", "Industry": "Finance", "Market Cap": 23327891029},
    "EQR": {"Company Name": "Equity Residential", "Industry": "Finance", "Market Cap": 23249571811},
    "IR": {"Company Name": "Ingersoll Rand Inc.", "Industry": "Producer Manufacturing", "Market Cap": 23238688587},
    "AEE": {"Company Name": "Ameren Corporation", "Industry": "Utilities", "Market Cap": 23202366219},
    "FRC": {"Company Name": "FIRST REPUBLIC BANK", "Industry": "Finance", "Market Cap": 22901145433},
    "TSN": {"Company Name": "Tyson Foods, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 22743994852},
    "BAX": {"Company Name": "Baxter International Inc.", "Industry": "Health Technology", "Market Cap": 22730805058},
    "PPL": {"Company Name": "PPL Corporation", "Industry": "Utilities", "Market Cap": 22619697619},
    "VRSN": {"Company Name": "VeriSign, Inc.", "Industry": "Technology Services", "Market Cap": 22575144528},
    "LH": {"Company Name": "Laboratory Corporation of America Holdings", "Industry": "Health Services", "Market Cap": 22356437777},
    "LUV": {"Company Name": "Southwest Airlines Company", "Industry": "Transportation", "Market Cap": 21951012688},
    "ANSS": {"Company Name": "ANSYS, Inc.", "Industry": "Technology Services", "Market Cap": 21949670217},
    "MLM": {"Company Name": "Martin Marietta Materials, Inc.", "Industry": "Non-Energy Minerals", "Market Cap": 21829845513},
    "ETR": {"Company Name": "Entergy Corporation", "Industry": "Utilities", "Market Cap": 21740193258},
    "MKC": {"Company Name": "McCormick & Company, Incorporated", "Industry": "Consumer Non-Durables", "Market Cap": 21714785875},
    "PFG": {"Company Name": "Principal Financial Group Inc", "Industry": "Finance", "Market Cap": 21620172383},
    "HBAN": {"Company Name": "Huntington Bancshares Incorporated", "Industry": "Finance", "Market Cap": 21136056255},
    "PWR": {"Company Name": "Quanta Services, Inc.", "Industry": "Industrial Services", "Market Cap": 21122219159},
    "XYL": {"Company Name": "Xylem Inc.", "Industry": "Producer Manufacturing", "Market Cap": 20939939674},
    "HPE": {"Company Name": "Hewlett Packard Enterprise Company", "Industry": "Electronic Technology", "Market Cap": 20919251328},
    "RF": {"Company Name": "Regions Financial Corporation", "Industry": "Finance", "Market Cap": 20894204582},
    "EXR": {"Company Name": "Extra Space Storage Inc", "Industry": "Finance", "Market Cap": 20638646153},
    "CFG": {"Company Name": "Citizens Financial Group, Inc.", "Industry": "Finance", "Market Cap": 20600898043},
    "VTR": {"Company Name": "Ventas, Inc.", "Industry": "Finance", "Market Cap": 20457230346},
    "NTRS": {"Company Name": "Northern Trust Corporation", "Industry": "Finance", "Market Cap": 20285097024},
    "CAH": {"Company Name": "Cardinal Health, Inc.", "Industry": "Distribution Services", "Market Cap": 20058495341},
    "DOV": {"Company Name": "Dover Corporation", "Industry": "Producer Manufacturing", "Market Cap": 20056579760},
    "CTRA": {"Company Name": "Coterra Energy Inc.", "Industry": "Energy Minerals", "Market Cap": 20019185439},
    "STE": {"Company Name": "STERIS plc (Ireland)", "Industry": "Health Technology", "Market Cap": 19987549307},
    "WAT": {"Company Name": "Waters Corporation", "Industry": "Health Technology", "Market Cap": 19943123216},
    "CHD": {"Company Name": "Church & Dwight Company, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 19848444627},
    "HOLX": {"Company Name": "Hologic, Inc.", "Industry": "Health Technology", "Market Cap": 19634743945},
    "EPAM": {"Company Name": "EPAM Systems, Inc.", "Industry": "Technology Services", "Market Cap": 19611523974},
    "CNP": {"Company Name": "CenterPoint Energy, Inc (Holding Co)", "Industry": "Utilities", "Market Cap": 19559672283},
    "TDY": {"Company Name": "Teledyne Technologies Incorporated", "Industry": "Electronic Technology", "Market Cap": 19504468471},
    "WRB": {"Company Name": "W.R. Berkley Corporation", "Industry": "Finance", "Market Cap": 19387721834},
    "STLD": {"Company Name": "Steel Dynamics, Inc.", "Industry": "Non-Energy Minerals", "Market Cap": 19377817129},
    "INVH": {"Company Name": "Invitation Homes Inc.", "Industry": "Finance", "Market Cap": 19204385246},
    "CAG": {"Company Name": "ConAgra Brands, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 19126861336},
    "BBY": {"Company Name": "Best Buy Co., Inc.", "Industry": "Retail Trade", "Market Cap": 19117248824},
    "FSLR": {"Company Name": "First Solar, Inc.", "Industry": "Electronic Technology", "Market Cap": 19066413298},
    "WAB": {"Company Name": "Westinghouse Air Brake Technologies Corporation", "Industry": "Producer Manufacturing", "Market Cap": 18839690836},
    "GRMN": {"Company Name": "Garmin Ltd.", "Industry": "Electronic Technology", "Market Cap": 18811816046},
    "MPWR": {"Company Name": "Monolithic Power Systems, Inc.", "Industry": "Electronic Technology", "Market Cap": 18759902104},
    "CMS": {"Company Name": "CMS Energy Corporation", "Industry": "Utilities", "Market Cap": 18674786039},
    "JBHT": {"Company Name": "J.B. Hunt Transport Services, Inc.", "Industry": "Transportation", "Market Cap": 18600497263},
    "MAA": {"Company Name": "Mid-America Apartment Communities, Inc.", "Industry": "Finance", "Market Cap": 18532906392},
    "AES": {"Company Name": "The AES Corporation", "Industry": "Utilities", "Market Cap": 18495529434},
    "ROL": {"Company Name": "Rollins, Inc.", "Industry": "Consumer Services", "Market Cap": 18492339845},
    "ALGN": {"Company Name": "Align Technology, Inc.", "Industry": "Health Technology", "Market Cap": 18401707665},
    "WST": {"Company Name": "West Pharmaceutical Services, Inc.", "Industry": "Health Technology", "Market Cap": 18366842202},
    "PAYC": {"Company Name": "Paycom Software, Inc.", "Industry": "Technology Services", "Market Cap": 18262997097},
    "AMCR": {"Company Name": "Amcor plc", "Industry": "Process Industries", "Market Cap": 18166037997},
    "DRI": {"Company Name": "Darden Restaurants, Inc.", "Industry": "Consumer Services", "Market Cap": 18097577646},
    "BALL": {"Company Name": "Ball Corporation", "Industry": "Process Industries", "Market Cap": 17940537967},
    "INCY": {"Company Name": "Incyte Corporation", "Industry": "Health Technology", "Market Cap": 17898150389},
    "IEX": {"Company Name": "IDEX Corporation", "Industry": "Producer Manufacturing", "Market Cap": 17818237724},
    "CLX": {"Company Name": "Clorox Company (The)", "Industry": "Consumer Non-Durables", "Market Cap": 17621817489},
    "EXPD": {"Company Name": "Expeditors International of Washington, Inc.", "Industry": "Transportation", "Market Cap": 17554334026},
    "TTWO": {"Company Name": "Take-Two Interactive Software, Inc.", "Industry": "Technology Services", "Market Cap": 17501856420},
    "MOH": {"Company Name": "Molina Healthcare Inc", "Industry": "Health Services", "Market Cap": 17470360100},
    "BRO": {"Company Name": "Brown & Brown, Inc.", "Industry": "Finance", "Market Cap": 17463492006},
    "MRO": {"Company Name": "Marathon Oil Corporation", "Industry": "Energy Minerals", "Market Cap": 17388156106},
    "SEDG": {"Company Name": "SolarEdge Technologies, Inc.", "Industry": "Producer Manufacturing", "Market Cap": 17297227408},
    "COO": {"Company Name": "The Cooper Companies, Inc.", "Industry": "Health Technology", "Market Cap": 17246889239},
    "OMC": {"Company Name": "Omnicom Group Inc.", "Industry": "Commercial Services", "Market Cap": 17200324616},
    "KEY": {"Company Name": "KeyCorp", "Industry": "Finance", "Market Cap": 17110661569},
    "TRGP": {"Company Name": "Targa Resources, Inc.", "Industry": "Utilities", "Market Cap": 17070969496},
    "BR": {"Company Name": "Broadridge Financial Solutions, Inc.", "Industry": "Technology Services", "Market Cap": 17058845379},
    "FOX": {"Company Name": "Fox Corporation", "Industry": "Consumer Services", "Market Cap": 17009331524},
    "FOXA": {"Company Name": "Fox Corporation", "Industry": "Consumer Services", "Market Cap": 17009331524},
    "CINF": {"Company Name": "Cincinnati Financial Corporation", "Industry": "Finance", "Market Cap": 16964902725},
    "CF": {"Company Name": "CF Industries Holdings, Inc.", "Industry": "Process Industries", "Market Cap": 16933112537},
    "LYV": {"Company Name": "Live Nation Entertainment, Inc.", "Industry": "Consumer Services", "Market Cap": 16888862664},
    "DGX": {"Company Name": "Quest Diagnostics Incorporated", "Industry": "Health Services", "Market Cap": 16869010972},
    "HWM": {"Company Name": "Howmet Aerospace Inc.", "Industry": "Electronic Technology", "Market Cap": 16825667752},
    "UAL": {"Company Name": "United Airlines Holdings, Inc.", "Industry": "Transportation", "Market Cap": 16771398786},
    "PKI": {"Company Name": "PerkinElmer, Inc.", "Industry": "Health Technology", "Market Cap": 16693913190},
    "SJM": {"Company Name": "J.M. Smucker Company (The) New", "Industry": "Consumer Non-Durables", "Market Cap": 16566370477},
    "ETSY": {"Company Name": "Etsy, Inc.", "Industry": "Retail Trade", "Market Cap": 16544352690},
    "ATO": {"Company Name": "Atmos Energy Corporation", "Industry": "Utilities", "Market Cap": 16398008384},
    "CPB": {"Company Name": "Campbell Soup Company", "Industry": "Consumer Non-Durables", "Market Cap": 16389859412},
    "FMC": {"Company Name": "FMC Corporation", "Industry": "Process Industries", "Market Cap": 16297471279},
    "SWKS": {"Company Name": "Skyworks Solutions, Inc.", "Industry": "Electronic Technology", "Market Cap": 16216306973},
    "J": {"Company Name": "Jacobs Solutions Inc.", "Industry": "Industrial Services", "Market Cap": 16183451146},
    "EXPE": {"Company Name": "Expedia Group, Inc.", "Industry": "Consumer Services", "Market Cap": 16085945747},
    "MOS": {"Company Name": "Mosaic Company (The)", "Industry": "Process Industries", "Market Cap": 15995798073},
    "RCL": {"Company Name": "D/B/A Royal Caribbean Cruises Ltd.", "Industry": "Consumer Services", "Market Cap": 15933565109},
    "FDS": {"Company Name": "FactSet Research Systems Inc.", "Industry": "Technology Services", "Market Cap": 15831666445},
    "NVR": {"Company Name": "NVR, Inc.", "Industry": "Consumer Durables", "Market Cap": 15768505720},
    "AVY": {"Company Name": "Avery Dennison Corporation", "Industry": "Process Industries", "Market Cap": 15625400560},
    "LKQ": {"Company Name": "LKQ Corporation", "Industry": "Consumer Durables", "Market Cap": 15496149292},
    "PTC": {"Company Name": "PTC Inc.", "Industry": "Technology Services", "Market Cap": 15399400065},
    "IRM": {"Company Name": "Iron Mountain Incorporated (Delaware)", "Industry": "Finance", "Market Cap": 15160736575},
    "SYF": {"Company Name": "Synchrony Financial", "Industry": "Finance", "Market Cap": 15129182477},
    "ZBRA": {"Company Name": "Zebra Technologies Corporation", "Industry": "Electronic Technology", "Market Cap": 15127529957},
    "SIVB": {"Company Name": "SVB Financial Group", "Industry": "Finance", "Market Cap": 15001809688},
    "TER": {"Company Name": "Teradyne, Inc.", "Industry": "Electronic Technology", "Market Cap": 14974394631},
    "MGM": {"Company Name": "MGM Resorts International", "Industry": "Consumer Services", "Market Cap": 14949910170},
    "TXT": {"Company Name": "Textron Inc.", "Industry": "Electronic Technology", "Market Cap": 14914634263},
    "BEN": {"Company Name": "Franklin Resources, Inc.", "Industry": "Finance", "Market Cap": 14901832813},
    "PEAK": {"Company Name": "Healthpeak Properties, Inc.", "Industry": "Finance", "Market Cap": 14822195369},
    "EVRG": {"Company Name": "Evergy, Inc.", "Industry": "Utilities", "Market Cap": 14671965770},
    "APA": {"Company Name": "APA Corporation", "Industry": "Energy Minerals", "Market Cap": 14580560107},
    "FLT": {"Company Name": "FleetCor Technologies, Inc.", "Industry": "Commercial Services", "Market Cap": 14346308893},
    "GEN": {"Company Name": "Gen Digital Inc.", "Industry": "Technology Services", "Market Cap": 14303862001},
    "ESS": {"Company Name": "Essex Property Trust, Inc.", "Industry": "Finance", "Market Cap": 14278216141},
    "L": {"Company Name": "Loews Corporation", "Industry": "Finance", "Market Cap": 14217131872},
    "VTRS": {"Company Name": "Viatris Inc.", "Industry": "Health Technology", "Market Cap": 14139901905},
    "LNT": {"Company Name": "Alliant Energy Corporation", "Industry": "Utilities", "Market Cap": 14007018220},
    "LW": {"Company Name": "Lamb Weston Holdings, Inc.", "Industry": "Consumer Non-Durables", "Market Cap": 13964079135},
    "IPG": {"Company Name": "Interpublic Group of Companies, Inc. (The)", "Industry": "Commercial Services", "Market Cap": 13959693281},
    "AKAM": {"Company Name": "Akamai Technologies, Inc.", "Industry": "Technology Services", "Market Cap": 13937956872},
    "NDSN": {"Company Name": "Nordson Corporation", "Industry": "Producer Manufacturing", "Market Cap": 13840525072},
    "NTAP": {"Company Name": "NetApp, Inc.", "Industry": "Electronic Technology", "Market Cap": 13807474639},
    "RE": {"Company Name": "Everest Re Group, Ltd.", "Industry": "Finance", "Market Cap": 13692487399},
    "BIO": {"Company Name": "Bio-Rad Laboratories, Inc.", "Industry": "Health Technology", "Market Cap": 13554965601},
    "POOL": {"Company Name": "Pool Corporation", "Industry": "Distribution Services", "Market Cap": 13542363879},
    "LDOS": {"Company Name": "Leidos Holdings, Inc.", "Industry": "Electronic Technology", "Market Cap": 13492626336},
    "IP": {"Company Name": "International Paper Company", "Industry": "Process Industries", "Market Cap": 13451439799},
    "KIM": {"Company Name": "Kimco Realty Corporation (HC)", "Industry": "Finance", "Market Cap": 13421094191},
    "TRMB": {"Company Name": "Trimble Inc.", "Industry": "Electronic Technology", "Market Cap": 13352260827},
    "PARA": {"Company Name": "Paramount Global", "Industry": "Consumer Services", "Market Cap": 13273635762},
    "JKHY": {"Company Name": "Jack Henry & Associates, Inc.", "Industry": "Technology Services", "Market Cap": 13246887157},
    "SNA": {"Company Name": "Snap-On Incorporated", "Industry": "Consumer Durables", "Market Cap": 13195108175},
    "CE": {"Company Name": "Celanese Corporation", "Industry": "Process Industries", "Market Cap": 13189190377},
    "TYL": {"Company Name": "Tyler Technologies, Inc.", "Industry": "Technology Services", "Market Cap": 13181526708},
    "UDR": {"Company Name": "UDR, Inc.", "Industry": "Finance", "Market Cap": 13171420063},
    "SWK": {"Company Name": "Stanley Black & Decker, Inc.", "Industry": "Consumer Durables", "Market Cap": 13170433469},
    "CBOE": {"Company Name": "Cboe Global Markets, Inc.", "Industry": "Finance", "Market Cap": 13129789649},
    "TECH": {"Company Name": "Bio-Techne Corp", "Industry": "Health Technology", "Market Cap": 12898185845},
    "MTCH": {"Company Name": "Match Group, Inc.", "Industry": "Technology Services", "Market Cap": 12864838949},
    "EQT": {"Company Name": "EQT Corporation", "Industry": "Energy Minerals", "Market Cap": 12831927474},
    "CCL": {"Company Name": "Carnival Corporation", "Industry": "Consumer Services", "Market Cap": 12731758647},
    "CPT": {"Company Name": "Camden Property Trust", "Industry": "Finance", "Market Cap": 12605462032},
    "PKG": {"Company Name": "Packaging Corporation of America", "Industry": "Process Industries", "Market Cap": 12581912982},
    "HST": {"Company Name": "Host Hotels", "Industry": "Finance", "Market Cap": 12441482943},
    "MKTX": {"Company Name": "MarketAxess Holdings, Inc.", "Industry": "Finance", "Market Cap": 12179652569},
    "WDC": {"Company Name": "Western Digital Corporation", "Industry": "Electronic Technology", "Market Cap": 12058003904},
    "DPZ": {"Company Name": "Domino's Pizza Inc", "Industry": "Consumer Services", "Market Cap": 11952616095},
    "VFC": {"Company Name": "V.F. Corporation", "Industry": "Consumer Non-Durables", "Market Cap": 11948407608},
    "STX": {"Company Name": "Seagate Technology Holdings PLC", "Industry": "Electronic Technology", "Market Cap": 11926868527},
    "CRL": {"Company Name": "Charles River Laboratories International, Inc.", "Industry": "Commercial Services", "Market Cap": 11816567503},
    "GL": {"Company Name": "Globe Life Inc.", "Industry": "Finance", "Market Cap": 11806659707},
    "MAS": {"Company Name": "Masco Corporation", "Industry": "Producer Manufacturing", "Market Cap": 11698195682},
    "PHM": {"Company Name": "PulteGroup, Inc.", "Industry": "Consumer Durables", "Market Cap": 11461610296},
    "REG": {"Company Name": "Regency Centers Corporation", "Industry": "Finance", "Market Cap": 11427246579},
    "NI": {"Company Name": "NiSource Inc", "Industry": "Utilities", "Market Cap": 11331147886},
    "NWS": {"Company Name": "News Corporation", "Industry": "Consumer Services", "Market Cap": 11209910324},
    "NWSA": {"Company Name": "News Corporation", "Industry": "Consumer Services", "Market Cap": 11209910324},
    "TFX": {"Company Name": "Teleflex Incorporated", "Industry": "Health Technology", "Market Cap": 11189060238},
    "WYNN": {"Company Name": "Wynn Resorts, Limited", "Industry": "Consumer Services", "Market Cap": 11173853278},
    "BXP": {"Company Name": "Boston Properties, Inc.", "Industry": "Finance", "Market Cap": 11164070991},
    "CHRW": {"Company Name": "C.H. Robinson Worldwide, Inc.", "Industry": "Transportation", "Market Cap": 11005834980},
    "TAP": {"Company Name": "Molson Coors Beverage Company", "Industry": "Consumer Non-Durables", "Market Cap": 10982976380},
    "EMN": {"Company Name": "Eastman Chemical Company", "Industry": "Process Industries", "Market Cap": 10950320882},
    "AAL": {"Company Name": "American Airlines Group, Inc.", "Industry": "Transportation", "Market Cap": 10937831742},
    "HSIC": {"Company Name": "Henry Schein, Inc.", "Industry": "Distribution Services", "Market Cap": 10777388129},
    "KMX": {"Company Name": "CarMax Inc", "Industry": "Retail Trade", "Market Cap": 10568611148},
    "BBWI": {"Company Name": "Bath & Body Works, Inc.", "Industry": "Retail Trade", "Market Cap": 10539050050},
    "BWA": {"Company Name": "BorgWarner Inc.", "Industry": "Producer Manufacturing", "Market Cap": 10445606990},
    "TPR": {"Company Name": "Tapestry, Inc.", "Industry": "Retail Trade", "Market Cap": 10385431822},
    "JNPR": {"Company Name": "Juniper Networks, Inc.", "Industry": "Electronic Technology", "Market Cap": 10285165299},
    "CDAY": {"Company Name": "Ceridian HCM Holding Inc.", "Industry": "Technology Services", "Market Cap": 10252457165},
    "CZR": {"Company Name": "Caesars Entertainment, Inc.", "Industry": "Consumer Services", "Market Cap": 10129666156},
    "QRVO": {"Company Name": "Qorvo, Inc.", "Industry": "Electronic Technology", "Market Cap": 10104475247},
    "ALLE": {"Company Name": "Allegion plc", "Industry": "Producer Manufacturing", "Market Cap": 9971265492},
    "WRK": {"Company Name": "Westrock Company", "Industry": "Process Industries", "Market Cap": 9511864190},
    "AOS": {"Company Name": "A.O. Smith Corporation", "Industry": "Producer Manufacturing", "Market Cap": 9380417640},
    "UHS": {"Company Name": "Universal Health Services, Inc.", "Industry": "Health Services", "Market Cap": 9379967097},
    "HII": {"Company Name": "Huntington Ingalls Industries, Inc.", "Industry": "Electronic Technology", "Market Cap": 9116760447},
    "HAS": {"Company Name": "Hasbro, Inc.", "Industry": "Consumer Durables", "Market Cap": 9098931742},
    "CMA": {"Company Name": "Comerica Incorporated", "Industry": "Finance", "Market Cap": 9023931955},
    "AAP": {"Company Name": "Advance Auto Parts Inc.", "Industry": "Retail Trade", "Market Cap": 9017823109},
    "FRT": {"Company Name": "Federal Realty Investment Trust", "Industry": "Finance", "Market Cap": 8938206224},
    "IVZ": {"Company Name": "Invesco Ltd", "Industry": "Finance", "Market Cap": 8900134619},
    "FFIV": {"Company Name": "F5, Inc.", "Industry": "Technology Services", "Market Cap": 8891088863},
    "CTLT": {"Company Name": "Catalent, Inc.", "Industry": "Health Technology", "Market Cap": 8881203017},
    "PNW": {"Company Name": "Pinnacle West Capital Corporation", "Industry": "Utilities", "Market Cap": 8621283305},
    "WHR": {"Company Name": "Whirlpool Corporation", "Industry": "Consumer Durables", "Market Cap": 8397293669},
    "RHI": {"Company Name": "Robert Half International Inc.", "Industry": "Commercial Services", "Market Cap": 8255653723},
    "PNR": {"Company Name": "Pentair plc.", "Industry": "Producer Manufacturing", "Market Cap": 8201887934},
    "DISH": {"Company Name": "DISH Network Corporation", "Industry": "Consumer Services", "Market Cap": 7992435656},
    "OGN": {"Company Name": "Organon & Co.", "Industry": "Health Technology", "Market Cap": 7981954985},
    "SEE": {"Company Name": "Sealed Air Corporation", "Industry": "Process Industries", "Market Cap": 7902640280},
    "RL": {"Company Name": "Ralph Lauren Corporation", "Industry": "Distribution Services", "Market Cap": 7881330616},
    "XRAY": {"Company Name": "DENTSPLY SIRONA Inc.", "Industry": "Health Technology", "Market Cap": 7736828247},
    "ZION": {"Company Name": "Zions Bancorporation N.A.", "Industry": "Finance", "Market Cap": 7697833458},
    "MHK": {"Company Name": "Mohawk Industries, Inc.", "Industry": "Non-Energy Minerals", "Market Cap": 7568173937},
    "NRG": {"Company Name": "NRG Energy, Inc.", "Industry": "Utilities", "Market Cap": 7515132392},
    "SBNY": {"Company Name": "Signature Bank", "Industry": "Finance", "Market Cap": 7365097360},
    "GNRC": {"Company Name": "Generac Holdlings Inc.", "Industry": "Producer Manufacturing", "Market Cap": 7194119794},
    "DVA": {"Company Name": "DaVita Inc.", "Industry": "Health Services", "Market Cap": 7047621991},
    "AIZ": {"Company Name": "Assurant, Inc.", "Industry": "Finance", "Market Cap": 6656759995},
    "DXC": {"Company Name": "DXC Technology Company", "Industry": "Technology Services", "Market Cap": 6630479457},
    "NCLH": {"Company Name": "Norwegian Cruise Line Holdings Ltd.", "Industry": "Consumer Services", "Market Cap": 6468430106},
    "ALK": {"Company Name": "Alaska Air Group, Inc.", "Industry": "Transportation", "Market Cap": 6265788975},
    "NWL": {"Company Name": "Newell Brands Inc.", "Industry": "Producer Manufacturing", "Market Cap": 6261904234},
    "LUMN": {"Company Name": "Lumen Technologies, Inc.", "Industry": "Communications", "Market Cap": 6248879853},
    "LNC": {"Company Name": "Lincoln National Corporation", "Industry": "Finance", "Market Cap": 5335363865}
}

