"""add constraint

Revision ID: 436918da51cb
Revises: 3b730a9145b4
Create Date: 2023-07-25 12:25:18.445959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436918da51cb'
down_revision = '3b730a9145b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stocks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stock_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stocks', schema=None) as batch_op:
        batch_op.alter_column('stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
