"""add shares column and constraints

Revision ID: 50f4e54ff6a6
Revises: 547bc2b5b367
Create Date: 2023-07-28 09:18:30.379092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f4e54ff6a6'
down_revision = '547bc2b5b367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stocks', schema=None) as batch_op:
        batch_op.drop_column('shares')

    # ### end Alembic commands ###
