"""add price column

Revision ID: 547bc2b5b367
Revises: 436918da51cb
Create Date: 2023-07-25 17:37:00.900569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547bc2b5b367'
down_revision = '436918da51cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
